-- MySQL Script generated by MySQL Workbench
-- Mon Jan  6 11:32:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `portfolio` ;

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;


-- -----------------------------------------------------
-- Table `portfolio`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`User` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`User` (
  `iduser` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `hash_password` LONGTEXT NULL,
  `lastlogin` DATETIME NULL,
  `aboutme` LONGTEXT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Job` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Job` (
  `idJob` INT NOT NULL,
  `companyname` VARCHAR(255) NULL,
  `started_at` DATE NULL,
  `ended_at` DATE NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `is_ended` TINYINT NULL,
  `user_iduser` INT NOT NULL,
  `role` LONGTEXT NULL,
  PRIMARY KEY (`idJob`),
  INDEX `fk_Job_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Job_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `portfolio`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Socialaccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Socialaccount` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Socialaccount` (
  `idSocialAccount` INT NOT NULL,
  `url` LONGTEXT NULL,
  `name` VARCHAR(100) NULL,
  `is_public` TINYINT NULL,
  `created_at` DATETIME NULL,
  `updated_at` VARCHAR(45) NULL,
  `imageurl` LONGTEXT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idSocialAccount`),
  INDEX `fk_SocialAccount_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_SocialAccount_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `portfolio`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Education` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Education` (
  `idEducation` INT NOT NULL,
  `degreename` VARCHAR(255) NULL,
  `institutename` VARCHAR(255) NULL,
  `instituteurl` LONGTEXT NULL,
  `started_at` VARCHAR(45) NULL,
  `ended_at` VARCHAR(45) NULL,
  `is_completed` VARCHAR(45) NULL,
  `creatd-at` DATE NULL,
  `updated-at` DATE NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idEducation`),
  INDEX `fk_Education_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Education_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `portfolio`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Skill` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Skill` (
  `idSkill` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `imageUrl` LONGTEXT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `is_public` TINYINT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idSkill`),
  INDEX `fk_Skill_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Skill_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `portfolio`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Project` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Project` (
  `idProject` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` LONGTEXT NULL,
  `created-at` DATETIME NULL,
  `updated-at` VARCHAR(45) NULL,
  `is_published` VARCHAR(45) NULL,
  `Projectcol` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  `is_opensource` TINYINT NULL,
  PRIMARY KEY (`idProject`),
  INDEX `fk_Project_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Project_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `portfolio`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Certification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Certification` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Certification` (
  `idCertification` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `url` LONGTEXT NULL,
  `created-at` DATETIME NULL,
  `updated_at` VARCHAR(45) NULL,
  `is_published` VARCHAR(45) NULL,
  `start-date` DATE NULL,
  `enddate` DATE NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idCertification`),
  INDEX `fk_Certification_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Certification_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `portfolio`.`User` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`Contactme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `portfolio`.`Contactme` ;

CREATE TABLE IF NOT EXISTS `portfolio`.`Contactme` (
  `idContactme` INT NOT NULL,
  `message` VARCHAR(300) NULL,
  `email` VARCHAR(100) NULL,
  `name` VARCHAR(60) NULL,
  `created_at` VARCHAR(45) NULL,
  `ip_address` VARCHAR(15) NULL,
  `borwser_information` LONGTEXT NULL,
  PRIMARY KEY (`idContactme`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
